Browser: add proxy config guide
FreeBSD-Ask/FreeBSD-Ask pull request #131
Opened 2023-10-10 12:09 UTC by Dedicatus5457

* chromium和firefox浏览器的代理配置.

Signed-off-by: yuuriko <ryanhou24@gmail.com>

2023-10-10 12:14 UTC, Dedicatus5457 commented
cc @ykla . 道长，你觉得这块应该挪到[第 7.1 节 HTTP 代理](https://book.bsdcn.org/di-7-zhang-vpn-yu-dai-li/di-7.1-jie-http-dai-li.html) 还是就放在现在浏览器配置那块（5.4节）？

2023-10-11 09:37 UTC, ykla commented
麻烦用 <https://try8.cn/tool/format/markdown> 格式化一下。移动到“[第 7.1 节 HTTP 代理](https://book.bsdcn.org/di-7-zhang-vpn-yu-dai-li/di-7.1-jie-http-dai-li.html)”吧。

2023-10-11 09:38 UTC, ykla requested changes
见上边的评论

2023-10-11 09:40 UTC, ykla commented on di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.4-jie-firefox-yu-chromium-an-zhuang.md
> +```
vim 后应有空格。

2023-10-11 09:42 UTC, ykla commented on di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.4-jie-firefox-yu-chromium-an-zhuang.md
> +
图片应该本地化，放入 `.gitbook/assets`。使用例子：`![图片介绍](../.gitbook/assets/图片名.png)`

2023-10-11 12:46 UTC, Dedicatus5457 commented
好的，明后天我有空会重新改一下。
________________________________
From: ykla ***@***.***>
Sent: Wednesday, October 11, 2023 5:43:10 PM
To: FreeBSD-Ask/FreeBSD-Ask ***@***.***>
Cc: Hou Qiyao ***@***.***>; Author ***@***.***>
Subject: Re: [FreeBSD-Ask/FreeBSD-Ask] Browser: add proxy config guide (PR #131)


@ykla commented on this pull request.

________________________________

In di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.4-jie-firefox-yu-chromium-an-zhuang.md<https://github.com/FreeBSD-Ask/FreeBSD-Ask/pull/131#discussion_r1354584722>:

> +Encoding=UTF-8
+Exec=chrome %U
+GenericName[zh_CN]=
+......
+```
+
+例:
+```
+Exec=chrome %U --proxy-server="192.168.2.163:20172"
+```
+#### 单独为Firefox配置代理
+
+因Firefox在windows GNU/linux Macos以及bsd的所有客户端的浏览器设置页面>网络设置选项卡中均有gui配置代理的模块，故此节不再赘述。
+
+<img decoding="async" src="https://i.mij.rip/2023/10/10/bffb29adb2fd30f0d3b7a008ac820a27.png" width="70%">
+


图片应该本地化，放入 .gitbook/assets。使用例子：![图片介绍](../.gitbook/assets/图片名.png)

―
Reply to this email directly, view it on GitHub<https://github.com/FreeBSD-Ask/FreeBSD-Ask/pull/131#pullrequestreview-1670627559>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASVBFOC4MLMPJBRJMXQOSLDX6ZS25ANCNFSM6AAAAAA52H2JGA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-10-12 06:35 UTC, merged

2023-10-12 06:39 UTC, ykla commented
你能试试解决 https://github.com/FreeBSD-Ask/FreeBSD-Ask/issues/121 吗

2023-10-12 09:52 UTC, Dedicatus5457 commented
> 你能试试解决 #121 吗

自己去chromium那申请api应该是像#121那样可用的，我们要测试的是chromium在freebsd上打包的版本这几个环境变量是否有效。。你想的也是测这个对吧。要是直接在教程里写分发的token那肯定不合适

![图片](https://github.com/FreeBSD-Ask/FreeBSD-Ask/assets/78254776/076cab5a-f4e8-4120-a67e-e10e2724c98b)
我稍后会整个token试试

2023-10-12 10:05 UTC, ykla commented
是看看 <https://gist.github.com/cvan/44a6d60457b20133191bd7b104f9dcc4 > 是否有效果、

2023-10-12 10:12 UTC, Dedicatus5457 commented
> 是看看 https://gist.github.com/cvan/44a6d60457b20133191bd7b104f9dcc4 是否有效果、

他划掉的那部分和我那第二个链接也就是他文里给的新链接是一样的，只是加了点图润色了一下。。反正目标都是定那个环境变量换成自己的token