create di-shi-er-jie-an-zhuang-i3wm.md
FreeBSD-Ask/FreeBSD-Ask pull request #27
Opened 2022-05-01 14:35 UTC by isNijikawa

Request review
issues #25

2022-05-02 12:18 UTC, ykla requested changes
不应该使用“```sh”。请去掉所有的 sh。

另外是否需要一个类似 lightdm 的窗口管理器？

以及，有无其他可以搭配这个桌面使用的软件，比如文泉驿字体？

2022-05-02 13:05 UTC, isNijikawa commented
> 不应该使用“```sh”。请去掉所有的 sh。
> 
> 另外是否需要一个类似 lightdm 的窗口管理器？
> 
> 以及，有无其他可以搭配这个桌面使用的软件，比如文泉驿字体？

"```sh" 是参考了一个 [markdown 规范](https://cirosantilli.com/markdown-style-guide/#option-code-fenced) 加上的, 如果执意要去掉也没问题.

我还没有在 FreeBSD 上尝试过各种显示管理器, 安装 i3 的前置 xorg 自带了一个 XDM, handbook 也有 [XDM 相关的介绍](https://docs.freebsd.org/en/books/handbook/x11/#x-xdm)相关的介绍, 我到时候会翻译一下.

i3wm 有一些 FreeBSD 已经支持的搭配软件, 比如常见的 i3lock 锁屏软件和 Nitrogen 壁纸管理器, 但是这些应用需要一定的篇幅的介绍, 我的计划是之后慢慢补充.

2022-05-02 15:46 UTC, ykla commented
handbook 我们有翻译的版本 https://handbook.freebsdcn.org

2022-05-03 09:39 UTC, ykla commented
合并完成。

<https://github.com/FreeBSD-Ask/FreeBSD-Ask/blob/main/di-er-shi-jiu-zhang-zhuo-mian-gao-ji-jin-jie/di-yi-jie-an-zhuang-i3wm.md>

2022-05-03 09:39 UTC, closed without merging